### ISSUE TITLE
How would you pass environment variables to React?

### ISSUE THREAD

**Issue by Udokah** [stolksdorf/vitreum#28]

**Comment by stolksdorf** [comment]
When you are doing [isomorphic rendering](https://github.com/stolksdorf/vitreum/blob/master/examples.md#isomorphic-server-rendering) you can load in your env-vars server-side (I prefer to use [nconf](https://www.npmjs.com/package/nconf)) and ass them through the render function, in the example where `url` and `coolProps` are. These will then  be passed as props to the top-level component you are rendering.
